version: '3.7'

services:
    mysql:
        # image: mariadb
        env_file: .env
        volumes:
            - db:/var/lib/mysql
        restart: always
        build: requirements/mariadb/
        networks:
            - main_network
        container_name: mariadb
    nginx:
        # image: nginx
        env_file: .env
        volumes:
            - wp:/var/www/html
        depends_on: 
            - wp
        ports: 
            - "443:443"
        restart: always
        build: requirements/nginx/
        networks:
            - main_network
        container_name: nginx
    wp:
        # image: wordpress
        env_file: .env
        volumes:
            - wp:/var/www/html
        depends_on: 
            - mysql
        restart: always
        build: requirements/wordpress/
        networks:
            - main_network
        container_name: wordpress

volumes:
    wp:
        driver: local
        name: wordpress
        driver_opts: 
            type: none
            o: bind
            device: /Users/kgeorgia/data/wp
            # device: /home/kgeorgia/data/wp
    db:
        driver: local
        name: db
        driver_opts: 
            type: none
            o: bind
            device: /Users/kgeorgia/data/db
            # device: /home/kgeorgia/data/db
        
networks:
    main_network:
        name: main_network
        driver: bridge